/**
 * G-Code Generator
 *
 * Generates CNC G-code from geometry for various machine types.
 */

import type {
  GCodeConfig,
  GCodeProgram,
  GCodeOperation,
  GCodeTool,
  ToolpathSegment,
} from '../types';
import type { GeometryResult } from '../../geometry/types';
import type { Point3D } from '../../knowledge/types';

// ============================================================================
// DEFAULT CONFIGURATIONS
// ============================================================================

export const defaultMillConfig: GCodeConfig = {
  machineType: 'mill-3axis',
  controller: 'fanuc',
  wcs: 'G54',
  units: 'mm',
  safetyHeight: 25,
  rapidFeed: 5000,
  cuttingFeed: 500,
  spindleSpeed: 3000,
  coolant: 'flood',
  toolChange: 'atc',
};

export const defaultLatheConfig: GCodeConfig = {
  machineType: 'lathe',
  controller: 'fanuc',
  wcs: 'G54',
  units: 'mm',
  safetyHeight: 50,
  rapidFeed: 10000,
  cuttingFeed: 200,
  spindleSpeed: 1500,
  coolant: 'flood',
  toolChange: 'atc',
};

export const defaultRouterConfig: GCodeConfig = {
  machineType: 'router',
  controller: 'grbl',
  wcs: 'G54',
  units: 'mm',
  safetyHeight: 10,
  rapidFeed: 3000,
  cuttingFeed: 1000,
  spindleSpeed: 18000,
  coolant: 'off',
  toolChange: 'manual',
};

// ============================================================================
// G-CODE GENERATOR CLASS
// ============================================================================

export class GCodeGenerator {
  private config: GCodeConfig;
  private currentTool: number = 0;

  constructor(config: Partial<GCodeConfig> = {}) {
    this.config = { ...defaultMillConfig, ...config };
  }

  /**
   * Generate G-code program from geometry
   */
  generateProgram(
    _geometry: GeometryResult,
    operations: ToolpathOperation[]
  ): GCodeProgram {
    const gcode: GCodeOperation[] = [];
    const toolList: GCodeTool[] = [];
    const warnings: string[] = [];

    // Collect unique tools
    for (const op of operations) {
      if (op.tool && !toolList.find(t => t.number === op.tool!.number)) {
        toolList.push(op.tool);
      }
    }

    // Generate program header
    const header = this.generateHeader();

    // Generate operations
    for (const op of operations) {
      const opGCode = this.generateOperation(op);
      gcode.push(...opGCode);
    }

    // Generate footer
    const footer = this.generateFooter();

    // Estimate machining time
    const estimatedTime = this.estimateTime(gcode);

    return {
      config: this.config,
      header,
      operations: gcode,
      footer,
      toolList,
      estimatedTime,
      warnings,
    };
  }

  /**
   * Generate program header
   */
  private generateHeader(): string[] {
    const header: string[] = [];

    // Program number
    if (this.config.programNumber) {
      header.push(`O${this.config.programNumber.toString().padStart(4, '0')}`);
    }

    // Program comment
    if (this.config.programComment) {
      header.push(`(${this.config.programComment})`);
    }

    header.push(`(Generated by MayhemAI)`);
    header.push(`(Date: ${new Date().toISOString()})`);
    header.push('');

    // Safety block
    header.push('G17 G40 G49 G80 G90'); // XY plane, cancel cutter comp, cancel length offset, cancel canned cycle, absolute mode

    // Unit selection
    header.push(this.config.units === 'mm' ? 'G21' : 'G20');

    // Work coordinate system
    header.push(this.config.wcs);

    header.push('');

    return header;
  }

  /**
   * Generate program footer
   */
  private generateFooter(): string[] {
    const footer: string[] = [];

    footer.push('');
    footer.push('M05'); // Spindle stop
    footer.push('M09'); // Coolant off
    footer.push(`G00 Z${this.config.safetyHeight}`); // Retract
    footer.push('G28 G91 Z0'); // Return to reference point
    footer.push('G28 X0 Y0'); // Return XY to reference
    footer.push('M30'); // Program end

    return footer;
  }

  /**
   * Generate G-code for a single operation
   */
  private generateOperation(operation: ToolpathOperation): GCodeOperation[] {
    const gcode: GCodeOperation[] = [];

    // Tool change if needed
    if (operation.tool && operation.tool.number !== this.currentTool) {
      gcode.push(...this.generateToolChange(operation.tool));
      this.currentTool = operation.tool.number;
    }

    // Spindle start
    if (operation.spindleSpeed) {
      gcode.push({
        type: 'spindle',
        params: {
          speed: operation.spindleSpeed,
          direction: 'cw',
        },
      });
    }

    // Coolant
    if (operation.coolant && operation.coolant !== 'off') {
      gcode.push({
        type: 'coolant',
        params: { mode: operation.coolant },
      });
    }

    // Move to start position
    if (operation.startPoint) {
      gcode.push({
        type: 'rapid',
        params: { z: this.config.safetyHeight },
      });
      gcode.push({
        type: 'rapid',
        params: {
          x: operation.startPoint.x,
          y: operation.startPoint.y,
        },
      });
    }

    // Execute toolpath segments
    for (const segment of operation.segments) {
      gcode.push(...this.generateSegment(segment));
    }

    // Retract after operation
    gcode.push({
      type: 'rapid',
      params: { z: this.config.safetyHeight },
    });

    return gcode;
  }

  /**
   * Generate G-code for a toolpath segment
   */
  private generateSegment(segment: ToolpathSegment): GCodeOperation[] {
    const gcode: GCodeOperation[] = [];

    switch (segment.type) {
      case 'rapid':
        gcode.push({
          type: 'rapid',
          params: {
            x: segment.end.x,
            y: segment.end.y,
            z: segment.end.z,
          },
        });
        break;

      case 'linear':
        gcode.push({
          type: 'linear',
          params: {
            x: segment.end.x,
            y: segment.end.y,
            z: segment.end.z,
            f: segment.feedRate || this.config.cuttingFeed,
          },
        });
        break;

      case 'arc':
        if (segment.center) {
          const i = segment.center.x - segment.start.x;
          const j = segment.center.y - segment.start.y;

          gcode.push({
            type: segment.clockwise ? 'arc-cw' : 'arc-ccw',
            params: {
              x: segment.end.x,
              y: segment.end.y,
              z: segment.end.z,
              i,
              j,
              f: segment.feedRate || this.config.cuttingFeed,
            },
          });
        }
        break;
    }

    return gcode;
  }

  /**
   * Generate tool change sequence
   */
  private generateToolChange(tool: GCodeTool): GCodeOperation[] {
    const gcode: GCodeOperation[] = [];

    gcode.push({
      type: 'comment',
      params: { text: `Tool ${tool.number}: ${tool.description}` },
    });

    // Retract to safe position
    gcode.push({
      type: 'rapid',
      params: { z: this.config.safetyHeight },
    });

    // Stop spindle
    gcode.push({
      type: 'spindle',
      params: { speed: 0, direction: 'stop' },
    });

    // Tool change
    if (this.config.toolChange === 'atc') {
      gcode.push({
        type: 'tool-change',
        params: { tool: tool.number },
      });
    } else if (this.config.toolChange === 'manual') {
      gcode.push({
        type: 'comment',
        params: { text: 'Manual tool change required' },
      });
      gcode.push({
        type: 'dwell',
        params: { seconds: 0 },
      }); // M00 optional stop
    }

    return gcode;
  }

  /**
   * Estimate machining time
   */
  private estimateTime(operations: GCodeOperation[]): number {
    let totalTime = 0;
    let currentPos = { x: 0, y: 0, z: 0 };

    for (const op of operations) {
      if (op.type === 'rapid' || op.type === 'linear') {
        const endPos = {
          x: (op.params.x as number) ?? currentPos.x,
          y: (op.params.y as number) ?? currentPos.y,
          z: (op.params.z as number) ?? currentPos.z,
        };

        const distance = Math.sqrt(
          Math.pow(endPos.x - currentPos.x, 2) +
          Math.pow(endPos.y - currentPos.y, 2) +
          Math.pow(endPos.z - currentPos.z, 2)
        );

        const feed = op.type === 'rapid'
          ? this.config.rapidFeed
          : ((op.params.f as number) || this.config.cuttingFeed);

        totalTime += (distance / feed) * 60; // Convert to seconds

        currentPos = endPos;
      } else if (op.type === 'tool-change') {
        totalTime += 30; // Estimate 30 seconds per tool change
      } else if (op.type === 'dwell') {
        totalTime += (op.params.seconds as number) || 1;
      }
    }

    return totalTime;
  }

  /**
   * Convert operations to G-code string
   */
  programToString(program: GCodeProgram): string {
    const lines: string[] = [];

    // Header
    lines.push(...program.header);

    // Operations
    for (const op of program.operations) {
      lines.push(this.operationToString(op));
    }

    // Footer
    lines.push(...program.footer);

    return lines.join('\n');
  }

  /**
   * Convert single operation to G-code string
   */
  private operationToString(op: GCodeOperation): string {
    switch (op.type) {
      case 'rapid':
        return this.formatMove('G00', op.params);

      case 'linear':
        return this.formatMove('G01', op.params);

      case 'arc-cw':
        return this.formatMove('G02', op.params);

      case 'arc-ccw':
        return this.formatMove('G03', op.params);

      case 'dwell':
        const seconds = op.params.seconds as number;
        return seconds === 0 ? 'M00' : `G04 P${seconds}`;

      case 'tool-change':
        return `T${op.params.tool} M06`;

      case 'spindle':
        const speed = op.params.speed as number;
        const dir = op.params.direction as string;
        if (speed === 0 || dir === 'stop') {
          return 'M05';
        }
        return `S${speed} ${dir === 'cw' ? 'M03' : 'M04'}`;

      case 'coolant':
        const mode = op.params.mode as string;
        switch (mode) {
          case 'flood': return 'M08';
          case 'mist': return 'M07';
          case 'through-tool': return 'M88';
          default: return 'M09';
        }

      case 'comment':
        return `(${op.params.text})`;

      default:
        return '';
    }
  }

  /**
   * Format move command
   */
  private formatMove(gcode: string, params: Record<string, number | string | boolean>): string {
    const parts = [gcode];

    if ('x' in params) parts.push(`X${this.formatNumber(params.x as number)}`);
    if ('y' in params) parts.push(`Y${this.formatNumber(params.y as number)}`);
    if ('z' in params) parts.push(`Z${this.formatNumber(params.z as number)}`);
    if ('i' in params) parts.push(`I${this.formatNumber(params.i as number)}`);
    if ('j' in params) parts.push(`J${this.formatNumber(params.j as number)}`);
    if ('k' in params) parts.push(`K${this.formatNumber(params.k as number)}`);
    if ('f' in params) parts.push(`F${Math.round(params.f as number)}`);

    return parts.join(' ');
  }

  /**
   * Format number for G-code
   */
  private formatNumber(value: number): string {
    return value.toFixed(3).replace(/\.?0+$/, '');
  }
}

// ============================================================================
// TOOLPATH OPERATION INTERFACE
// ============================================================================

export interface ToolpathOperation {
  name: string;
  type: 'contour' | 'pocket' | 'drill' | 'face' | 'thread' | 'groove';
  tool?: GCodeTool;
  spindleSpeed?: number;
  feedRate?: number;
  coolant?: 'off' | 'flood' | 'mist' | 'through-tool';
  startPoint?: Point3D;
  segments: ToolpathSegment[];
  depth?: number;
  stepover?: number;
  stepdown?: number;
}

// ============================================================================
// STANDARD TOOLS
// ============================================================================

export const standardEndmills: GCodeTool[] = [
  { number: 1, type: 'endmill', diameter: 6, length: 50, flutes: 4, material: 'carbide', description: '6mm 4-flute carbide' },
  { number: 2, type: 'endmill', diameter: 10, length: 75, flutes: 4, material: 'carbide', description: '10mm 4-flute carbide' },
  { number: 3, type: 'endmill', diameter: 12, length: 75, flutes: 4, material: 'carbide', description: '12mm 4-flute carbide' },
  { number: 4, type: 'endmill', diameter: 16, length: 100, flutes: 4, material: 'carbide', description: '16mm 4-flute carbide' },
  { number: 5, type: 'endmill', diameter: 20, length: 100, flutes: 4, material: 'carbide', description: '20mm 4-flute carbide' },
  { number: 6, type: 'endmill', diameter: 25, length: 125, flutes: 4, material: 'carbide', description: '25mm 4-flute carbide' },
];

export const standardDrills: GCodeTool[] = [
  { number: 10, type: 'drill', diameter: 3.3, length: 60, material: 'carbide', description: '3.3mm carbide drill (M4 tap)' },
  { number: 11, type: 'drill', diameter: 4.2, length: 70, material: 'carbide', description: '4.2mm carbide drill (M5 tap)' },
  { number: 12, type: 'drill', diameter: 5.0, length: 80, material: 'carbide', description: '5.0mm carbide drill (M6 tap)' },
  { number: 13, type: 'drill', diameter: 6.8, length: 90, material: 'carbide', description: '6.8mm carbide drill (M8 tap)' },
  { number: 14, type: 'drill', diameter: 8.5, length: 100, material: 'carbide', description: '8.5mm carbide drill (M10 tap)' },
  { number: 15, type: 'drill', diameter: 10.2, length: 110, material: 'carbide', description: '10.2mm carbide drill (M12 tap)' },
];

// ============================================================================
// FACTORY FUNCTION
// ============================================================================

export function createGCodeGenerator(
  machineType: 'mill' | 'lathe' | 'router',
  config?: Partial<GCodeConfig>
): GCodeGenerator {
  switch (machineType) {
    case 'mill':
      return new GCodeGenerator({ ...defaultMillConfig, ...config });
    case 'lathe':
      return new GCodeGenerator({ ...defaultLatheConfig, ...config });
    case 'router':
      return new GCodeGenerator({ ...defaultRouterConfig, ...config });
    default:
      return new GCodeGenerator(config);
  }
}
